# Generated by Django 2.2.5 on 2019-09-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=1)),
                ('link', models.URLField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=255)),
                ('salt', models.IntegerField(null=True)),
                ('carbohydrates', models.IntegerField(null=True)),
                ('sugars', models.IntegerField(null=True)),
                ('fats', models.IntegerField(null=True)),
                ('proteins', models.IntegerField(null=True)),
                ('fibers', models.IntegerField(null=True)),
                ('categories', models.ManyToManyField(to='substituter.Category')),
                ('stores', models.ManyToManyField(to='substituter.Store')),
            ],
        ),
    ]
