# Generated by Django 2.2.5 on 2019-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substituter', '0003_auto_20190918_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
